### ISSUE TITLE
Mobile Section problems

### ISSUE THREAD

**Issue by deslashh** [etho-black/ethoprotocol_website#31] opened 2021-04-04 10:33 UTC
Missing images + after the GIF behind the 'phone' ends, the whole section turns grey before it restarts.
![image](https://user-images.githubusercontent.com/81511499/113505741-1b65c780-9541-11eb-8721-4294345e4132.png)

**Comment by ghost** [comment] 2021-04-04 14:14
It is cause they are blank at the moment, @deslashh, if you can provide some snapshots with your personal information blurred, I can add them, there is a PR of mine pending to be merged that makes it a little better on both mobile and desktop, if the images can be somewhere around the below dimensions, I will create/update the PR

```
height: 375px 
width: 220px
```

**Comment by dylie** [comment] 2021-04-05 10:37
@newCodeRunner 

I've added the images in my previous commit. It works decent on mobile but on desk version for some reason it turns the images grey when not selected. Also, would it be possible to hide them and only show up once they reach the phone screen?
Also the CSS needs some edits on image positioning. Not entirely in center. Again fine on mobile tho.

Thanks in advance

![Screenshot_1](https://user-images.githubusercontent.com/38665633/113565659-9dbabe00-960b-11eb-8475-9b9c1b096d22.jpg)

**Comment by ghost** [comment] 2021-04-05 14:58
<img width="1440" alt="Screenshot 2021-04-05 at 7 56 22 PM" src="https://user-images.githubusercontent.com/57590297/113588026-0ffdc380-9649-11eb-835c-b3eb3bf8dd40.png">
I fixed the gray  issue, but I can't reproduce the position issue :( for me it looks like this

**Comment by ghost** [comment] 2021-04-05 15:29
added PR so that screen shots not in mobile do not show, as per @dylie's request

**Comment by dylie** [comment] 2021-04-05 15:41
Fixed

**Closed as completed by dylie** 2021-04-05 15:41 UTC
