### ISSUE TITLE
Scrolling problems.

### ISSUE THREAD

**Issue by deslashh** [etho-black/ethoprotocol_website#13] opened 2021-04-03 17:56 UTC
![image](https://user-images.githubusercontent.com/81511499/113487123-78686b80-94b6-11eb-9afa-a76ec95bba67.png)
Only "exchanges" works properly.
"Swaps" & "Bridges" always start from the top.(To makes things smoother)

**Comment by deslashh** [comment] 2021-04-03 17:56
![image](https://user-images.githubusercontent.com/81511499/113487157-b4033580-94b6-11eb-9916-0a7f1fc11f81.png)
"Partners" doesn't react.

**Comment by ghost** [comment] 2021-04-03 19:32
Can not reproduce the part related to Exchanges, swaps and bridges, which browser are you using? @deslashh

**Comment by deslashh** [comment] 2021-04-03 22:57
Edge, chrome, firefox.

**Comment by deslashh** [comment] 2021-04-03 22:57
> Can not reproduce the part related to Exchanges, swaps and bridges, which browser are you using? @deslashh

Edge, chrome, firefox.

**Comment by ghost** [comment] 2021-04-04 14:30
@deslashh, I can't reproduce it, I am using safari and chrome, there is different padding based on the section above, which gives the impression that it is not scrolling to top, but the div is always on top

**Comment by ghost** [comment] 2021-04-05 17:17
@dylie , can you produce this? if not we can close this

**Comment by dylie** [comment] 2021-04-06 13:50
Can reproduce, but not that big of a deal. Can be closed for now.

**Closed as completed by dylie** 2021-04-06 13:50 UTC
